### ISSUE TITLE
Dependancy with mycroft.util.log 

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-bus-client#2]
When I tried to run `ovos-listener`, I got an error related to `ovo-bus-client` about `mycroft.util.log`. Which means `mycroft`  still required to run this library.

Here is a part of the trace:
```
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/conf.py", line 8, in <module>
    from mycroft.util.log import LOG
ModuleNotFoundError: No module named 'mycroft'
```

I think `LOG` should be handled by `ovos-utils` if I'm not mistaking.

**Comment by JarbasAl** [comment]
fixed by #4
