### ISSUE TITLE
Bump dependency that restricts version of PyYAML

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-bus-client#28]
https://github.com/mikejgray/home-assistant-core/actions/runs/5021032857/jobs/9003050374

In order to create the Home Assistant OVOS integration, we need to be able to use PyYAML >= 6.0. At best we currently get 5.4.1.

**Comment by mikejgray** [comment]
[ovos-config has the proper version constraint](https://github.com/OpenVoiceOS/ovos-config/blob/dev/requirements/requirements.txt#L1) so I have to assume the issue is ovos-utils.

**Comment by goldyfruit** [comment]
> [ovos-config has the proper version constraint](https://github.com/OpenVoiceOS/ovos-config/blob/dev/requirements/requirements.txt#L1) so I have to assume the issue is ovos-utils.

If you want to get PyYAML 6.0 from `ovos-config` with `ovo-utils` you will have to install it with the `extras`.

**Comment by mikejgray** [comment]
> > [ovos-config has the proper version constraint](https://github.com/OpenVoiceOS/ovos-config/blob/dev/requirements/requirements.txt#L1) so I have to assume the issue is ovos-utils.
> 
> If you want to get PyYAML 6.0 from `ovos-config` with `ovo-utils` you will have to install it with the `extras`.

Thanks @goldyfruit , do you mean install `ovos-utils` with `extras`, or `ovos-config` with `extras`?

**Comment by goldyfruit** [comment]
> > > [ovos-config has the proper version constraint](https://github.com/OpenVoiceOS/ovos-config/blob/dev/requirements/requirements.txt#L1) so I have to assume the issue is ovos-utils.
> > 
> > 
> > If you want to get PyYAML 6.0 from `ovos-config` with `ovo-utils` you will have to install it with the `extras`.
> 
> Thanks @goldyfruit , do you mean install `ovos-utils` with `extras`, or `ovos-config` with `extras`?

```
pip install ovos-utils[extras]
```

**Comment by mikejgray** [comment]
Thanks @NeonDaniel , because installing with [extras] didn't help here

**Comment by NeonDaniel** [comment]
`ovos-utils[extras]` no longer required and ovos-config now supports pyyaml>5.4,<7.0
