### ISSUE TITLE
Latest git tag is invalid

### ISSUE THREAD

**Issue by PureTryOut** [OpenVoiceOS/ovos-bus-client#99]
Rather than a proper version it is just named `V`.
https://github.com/OpenVoiceOS/ovos-bus-client/releases/tag/V

**Comment by JarbasAl** [comment]
related hotfix so this issue didnt block pypi releases https://github.com/OpenVoiceOS/ovos-bus-client/commit/629f9ae8709ddd219312deeb276a7c130b96350b
